### PR TITLE
Added support for date types (date, time, timestamp).

### PR DESCRIPTION
**Pull request by mjbroek-bs**
With this change, .getMetadata() reports the correct java.sql.Date
type for columns marked as date. The .getDate() on a row also returns a
java.sql.Date object. Since jdbc expects dates to be in the GMT
timezone, the dates are converted first.

### CODE REVIEW

**Comment by julianhyde** [comment]
I had missed it -- thanks for bringing it to my attention. A couple of things:
1. Can you fix the build so that Travis CI passes. I think it's a checkfile exception.
2. Can you add a new data set rather than adding columns to EMP.csv. Add it in the src/test/resources/bug directory, and it will automatically show up as a table in the bug schema. I did something similar for `CsvTest.testWackyColumns`.
3. Time zones are a complicated business... and judging from your first name you are currently in GMT... we'll see whether they work correctly in other time zones. :)

Other than that, looks fine, and is useful functionality.

**Comment by mjbroek-bs** [comment]
I added the changes requested. The build passes and the dataset is now in new file. I also changed SimpleDateFormat to the threadsafe apache commons FastDateFormat and included the maven dependency. The changes are rebased to keep it into a single commit.

I am actually located in CET (Europe/Amsterdam) which currently is UTC+1. The code initializes the DateFormat in GMT so that the same date as in the csv gets returned by JDBC when reading resultSet.getDate(). Maybe an improvement someday could be to support timestamps with timezones included.

**Comment by julianhyde** [comment]
I'm merging now. As I surmised, there's a TZ issue when I run in PDT (UTC-7):

```
testWackyColumns(net.hydromatic.optiq.test.CsvTest)  Time elapsed: 0.087 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[joined at=2005-09-07; naME=Wilma, joined at=2007-01-01; naME=Alice]> but was:<[joined at=2005-09-06; naME=Wilma, joined at=2006-12-31; naME=Alice]>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at net.hydromatic.optiq.test.CsvTest$2.apply(CsvTest.java:187)
    at net.hydromatic.optiq.test.CsvTest$2.apply(CsvTest.java:182)
    at net.hydromatic.optiq.test.CsvTest.checkSql(CsvTest.java:208)
    at net.hydromatic.optiq.test.CsvTest.testWackyColumns(CsvTest.java:257)
```

Working on a solution for it.

**Comment by julianhyde** [comment]
The TZ issue was a bug in a test, not your code. We were calling `ResultSet.getObject(int).toString()`, which gives a `Date` or `Timestamp` object whose `toString` is locale-dependent -- when we should instead call `ResultSet.getString(int)`.

**Comment by julianhyde** [comment]
Merged as http://git-wip-us.apache.org/repos/asf/incubator-optiq-csv/commit/dd1b946c with further cleanup in http://git-wip-us.apache.org/repos/asf/incubator-optiq-csv/commit/3018d18c.

**Pull request closed without merging**
